---
- name: Pull and save Kafka image
  docker_image:
    name: confluentinc/cp-kafka:5.2.1
    source: pull
    archive_path: "{{ playbook_dir }}/artifacts/confluentinc_cp_kafka_5.2.1.tar"
    timeout: 300
  tags:
    - build_installer

- name: Load Kafka image
  docker_image:
    name: confluentinc/cp-kafka:5.1.3
    source: load
    load_path: "{{ playbook_dir }}/artifacts/confluentinc_cp_kafka_5.2.1.tar"

- name: Create Kafka data volume
  docker_volume:
    name: kafka_data

- name: Create Kafka container
  docker_container:
    name: kafka
    image: confluentinc/cp-kafka:5.2.1
    restart_policy: always
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - kafka
    purge_networks: yes
    published_ports:
      - 127.0.0.1:9093:9093
    volumes:
      - kafka_data:/var/lib/kafka/data
    env:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_LOG_RETENTION_HOURS: "-1"