---
- name: Download Docker binaries
  get_url:
    url: https://download.docker.com/linux/static/stable/x86_64/docker-18.09.6.tgz
    dest: "{{ playbook_dir }}/artifacts/docker-18.09.6.tgz"
  tags:
    - build_installer
