---
- name: Pull and save Zookeeper image
  docker_image:
    name: zookeeper:3.5
    source: pull
    archive_path: "{{ playbook_dir }}/artifacts/zookeeper_3.5.tar"
  tags:
    - build_installer

- name: Load Zookeeper image
  docker_image:
    load_path: "{{ playbook_dir }}/artifacts/zookeeper_3.5.tar"

- name: Create Zookeeper data volume
  docker_volume:
    name: zookeeper_data

- name: Create Zookeeper logs volume
  docker_volume:
    name: zookeeper_logs

- name: Create Zookeeper container
  docker_container:
    name: zookeeper
    image: zookeeper:3.5
    restart_policy: always
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - zookeeper
    purge_networks: yes
    volumes:
      - zookeeper_data:/data
      - zookeeper_logs:/datalog
    env:
      ZOO_MY_ID: 1
      ZOO_AUTOPURGE_PURGEINTERVAL: 3