---
- name: Pull and save Kibana image
  docker_image:
    name: kibana:6.8.0
    source: pull
    archive_path: "{{ playbook_dir }}/artifacts/kibana_6.8.0.tar"
    timeout: 300
  tags:
    - build_installer

- name: Load Kibana image
  docker_image:
    name: kibana:6.8.0
    source: load
    load_path: "{{ playbook_dir }}/artifacts/kibana_6.8.0.tar"

- name: Create Kibana container
  docker_container:
    name: kibana
    image: kibana:6.8.0
    restart_policy: always
    networks:
      - name: "{{ docker_network_name }}"
        aliases:
          - kibana
    purge_networks: yes
    published_ports:
      - 127.0.0.1:5601:5601
    env:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200