---
- name: Install Docker
  hosts: all
  connection: local
  roles:
    - docker

- name: Touch a test file
  hosts: all
  connection: local
  become: yes
  tasks:
    - name: Create file test.test
      file:
        path: /test.test
        state: touch
