---
- name: Install Docker
  hosts: all
  connection: local
  become: yes
  roles:
    - docker

- name: Manage an admin user
  hosts: all
  connection: local
  become: yes
  vars_files:
    - vars/global.yml
    - vars/passwords
  roles:
    - users

- name: Create common Docker network
  hosts: all
  connection: local
  become: yes
  vars_files:
    - vars/global.yml
  tasks:
    - name: Create common Docker network
      docker_network:
        name: "{{ docker_network_name }}"

- name: Install Zookeeper
  hosts: all
  connection: local
  become: yes
  vars_files:
    - vars/global.yml
  roles:
    - zookeeper

- name: Install Kafka
  hosts: all
  connection: local
  become: yes
  vars_files:
    - vars/global.yml
  roles:
    - kafka

- name: Install NiFi
  hosts: all
  connection: local
  become: yes
  vars_files:
    - vars/global.yml
  roles:
    - nifi

- name: Install MongoDB
  hosts: all
  connection: local
  become: yes
  vars_files:
    - vars/global.yml
    - vars/passwords
  roles:
    - mongo

- name: Install Elasticsearch
  hosts: all
  connection: local
  become: yes
  vars_files:
    - vars/global.yml
  roles:
    - elasticsearch

- name: Install Kibana
  hosts: all
  connection: local
  become: yes
  vars_files:
    - vars/global.yml
  roles:
    - kibana